CREATE TABLE `user` (
	`id` INT(11) NOT NULL AUTO_INCREMENT,
	`login_user` VARCHAR(100) NOT NULL DEFAULT '0',
	`senha_user` VARCHAR(100) NOT NULL DEFAULT '0',
	PRIMARY KEY (`id`)
)
COLLATE='latin1_swedish_ci'
ENGINE=InnoDB
AUTO_INCREMENT=4
;
